// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var org = org || {};

/**
 * @const
 * @namespace
 */
org.herbal3d = org.herbal3d || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol = org.herbal3d.protocol || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol.basil = org.herbal3d.protocol.basil || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol.basil.server = org.herbal3d.protocol.basil.server || {};

/**
 * @enum
 */
org.herbal3d.protocol.basil.server.BasilServerMsgMsg = {
  NONE: 0,
  DefineDisplayableObject: 1,
  CreateObjectInstance: 2,
  UpdateObjectProperty: 3,
  UpdateInstanceProperty: 4,
  UpdateInstancePosition: 5,
  ObjectPropertiesRequest: 6,
  InstancePropertiesRequest: 7,
  OpenSession: 8,
  CloseSession: 9,
  AliveCheck: 10,
  AliveResponse: 11
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.DefineDisplayableObject}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.DefineDisplayableObject=} obj
 * @returns {org.herbal3d.protocol.basil.server.DefineDisplayableObject}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.getRootAsDefineDisplayableObject = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.DefineDisplayableObject).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.assetInformation=} obj
 * @returns {org.herbal3d.protocol.basil.assetInformation}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.prototype.assetInfo = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.assetInformation).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.aaBoundingBox=} obj
 * @returns {org.herbal3d.protocol.basil.aaBoundingBox}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new org.herbal3d.protocol.basil.aaBoundingBox).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.startDefineDisplayableObject = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} assetInfoOffset
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.addAssetInfo = function(builder, assetInfoOffset) {
  builder.addFieldOffset(2, assetInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(3, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.DefineDisplayableObject.endDefineDisplayableObject = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.CreateObjectInstance}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.CreateObjectInstance=} obj
 * @returns {org.herbal3d.protocol.basil.server.CreateObjectInstance}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.getRootAsCreateObjectInstance = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.CreateObjectInstance).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.instancePositionInfo=} obj
 * @returns {org.herbal3d.protocol.basil.instancePositionInfo}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.instancePositionInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {org.herbal3d.protocol.basil.propertyValue=} obj
 * @returns {org.herbal3d.protocol.basil.propertyValue}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.propertiesToSet = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.prototype.propertiesToSetLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.startCreateObjectInstance = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.addPos = function(builder, posOffset) {
  builder.addFieldOffset(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertiesToSetOffset
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.addPropertiesToSet = function(builder, propertiesToSetOffset) {
  builder.addFieldOffset(3, propertiesToSetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.createPropertiesToSetVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.startPropertiesToSetVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.CreateObjectInstance.endCreateObjectInstance = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateObjectProperty}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateObjectProperty=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateObjectProperty}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.getRootAsUpdateObjectProperty = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateObjectProperty).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {org.herbal3d.protocol.basil.propertyValue=} obj
 * @returns {org.herbal3d.protocol.basil.propertyValue}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.prototype.props = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.prototype.propsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.startUpdateObjectProperty = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(2, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.createPropsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.startPropsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateObjectProperty.endUpdateObjectProperty = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstanceProperty}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateInstanceProperty=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstanceProperty}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.getRootAsUpdateInstanceProperty = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateInstanceProperty).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {org.herbal3d.protocol.basil.propertyValue=} obj
 * @returns {org.herbal3d.protocol.basil.propertyValue}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.props = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.propsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.startUpdateInstanceProperty = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(2, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.createPropsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.startPropsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.endUpdateInstanceProperty = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstancePosition}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateInstancePosition=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstancePosition}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.getRootAsUpdateInstancePosition = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateInstancePosition).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.instancePositionInfo=} obj
 * @returns {org.herbal3d.protocol.basil.instancePositionInfo}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.instancePositionInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.startUpdateInstancePosition = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addPos = function(builder, posOffset) {
  builder.addFieldOffset(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.endUpdateInstancePosition = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.ObjectPropertiesRequest}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.ObjectPropertiesRequest=} obj
 * @returns {org.herbal3d.protocol.basil.server.ObjectPropertiesRequest}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.getRootAsObjectPropertiesRequest = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.ObjectPropertiesRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.prototype.propertyMatch = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.startObjectPropertiesRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertyMatchOffset
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.addPropertyMatch = function(builder, propertyMatchOffset) {
  builder.addFieldOffset(2, propertyMatchOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.ObjectPropertiesRequest.endObjectPropertiesRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertiesRequest}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.InstancePropertiesRequest=} obj
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertiesRequest}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.getRootAsInstancePropertiesRequest = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.InstancePropertiesRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.prototype.propertyMatch = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.startInstancePropertiesRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertyMatchOffset
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.addPropertyMatch = function(builder, propertyMatchOffset) {
  builder.addFieldOffset(2, propertyMatchOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.InstancePropertiesRequest.endInstancePropertiesRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.OpenSession = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.OpenSession}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.OpenSession=} obj
 * @returns {org.herbal3d.protocol.basil.server.OpenSession}
 */
org.herbal3d.protocol.basil.server.OpenSession.getRootAsOpenSession = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.OpenSession).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {org.herbal3d.protocol.basil.propertyValue=} obj
 * @returns {org.herbal3d.protocol.basil.propertyValue}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.params = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyValue).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.paramsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.OpenSession.startOpenSession = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.OpenSession.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} paramsOffset
 */
org.herbal3d.protocol.basil.server.OpenSession.addParams = function(builder, paramsOffset) {
  builder.addFieldOffset(1, paramsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.OpenSession.createParamsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
org.herbal3d.protocol.basil.server.OpenSession.startParamsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.OpenSession.endOpenSession = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.CloseSession = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.CloseSession}
 */
org.herbal3d.protocol.basil.server.CloseSession.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.CloseSession=} obj
 * @returns {org.herbal3d.protocol.basil.server.CloseSession}
 */
org.herbal3d.protocol.basil.server.CloseSession.getRootAsCloseSession = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.CloseSession).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.CloseSession.prototype.reason = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.CloseSession.startCloseSession = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reasonOffset
 */
org.herbal3d.protocol.basil.server.CloseSession.addReason = function(builder, reasonOffset) {
  builder.addFieldOffset(0, reasonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.CloseSession.endCloseSession = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AliveCheck = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AliveCheck}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AliveCheck=} obj
 * @returns {org.herbal3d.protocol.basil.server.AliveCheck}
 */
org.herbal3d.protocol.basil.server.AliveCheck.getRootAsAliveCheck = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AliveCheck).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.sequenceNumber = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AliveCheck.startAliveCheck = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} time
 */
org.herbal3d.protocol.basil.server.AliveCheck.addTime = function(builder, time) {
  builder.addFieldInt64(0, time, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumber
 */
org.herbal3d.protocol.basil.server.AliveCheck.addSequenceNumber = function(builder, sequenceNumber) {
  builder.addFieldInt32(1, sequenceNumber, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AliveCheck.endAliveCheck = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AliveResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AliveResponse}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AliveResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.AliveResponse}
 */
org.herbal3d.protocol.basil.server.AliveResponse.getRootAsAliveResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AliveResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.sequenceNumber = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.timeReceived = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.sequenceNumberReceived = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AliveResponse.startAliveResponse = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} time
 */
org.herbal3d.protocol.basil.server.AliveResponse.addTime = function(builder, time) {
  builder.addFieldInt64(0, time, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumber
 */
org.herbal3d.protocol.basil.server.AliveResponse.addSequenceNumber = function(builder, sequenceNumber) {
  builder.addFieldInt32(1, sequenceNumber, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeReceived
 */
org.herbal3d.protocol.basil.server.AliveResponse.addTimeReceived = function(builder, timeReceived) {
  builder.addFieldInt64(2, timeReceived, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumberReceived
 */
org.herbal3d.protocol.basil.server.AliveResponse.addSequenceNumberReceived = function(builder, sequenceNumberReceived) {
  builder.addFieldInt32(3, sequenceNumberReceived, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AliveResponse.endAliveResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.BasilServerMsg = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.BasilServerMsg=} obj
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.getRootAsBasilServerMsg = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.BasilServerMsg).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.BTransportHdrStruct=} obj
 * @returns {org.herbal3d.protocol.basil.BTransportHdrStruct}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.BTransportHdr = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.BTransportHdrStruct).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsgMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.MsgType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {org.herbal3d.protocol.basil.server.BasilServerMsgMsg} */ (this.bb.readUint8(this.bb_pos + offset)) : org.herbal3d.protocol.basil.server.BasilServerMsgMsg.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.Msg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.startBasilServerMsg = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} BTransportHdrOffset
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addBTransportHdr = function(builder, BTransportHdrOffset) {
  builder.addFieldOffset(0, BTransportHdrOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {org.herbal3d.protocol.basil.server.BasilServerMsgMsg} MsgType
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addMsgType = function(builder, MsgType) {
  builder.addFieldInt8(1, MsgType, org.herbal3d.protocol.basil.server.BasilServerMsgMsg.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MsgOffset
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addMsg = function(builder, MsgOffset) {
  builder.addFieldOffset(2, MsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.endBasilServerMsg = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.org = org;
