// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var org = org || {};

/**
 * @const
 * @namespace
 */
org.herbal3d = org.herbal3d || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol = org.herbal3d.protocol || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol.basil = org.herbal3d.protocol.basil || {};

/**
 * @const
 * @namespace
 */
org.herbal3d.protocol.basil.server = org.herbal3d.protocol.basil.server || {};

/**
 * @enum
 */
org.herbal3d.protocol.basil.server.BasilServerMsgMsg = {
  NONE: 0,
  AddEntity: 1,
  RemoveEntity: 2,
  AddInstance: 3,
  RemoveInstance: 4,
  GetUniqueInstanceId: 5,
  GetUniqueInstanceIdResponse: 6,
  UpdateEntityProperty: 7,
  UpdateInstanceProperty: 8,
  UpdateInstancePosition: 9,
  EntityPropertyRequest: 10,
  EntityPropertyResponse: 11,
  InstancePropertyRequest: 12,
  InstancePropertyResponse: 13,
  OpenSession: 14,
  OpenSessionResponse: 15,
  CloseSession: 16,
  AliveCheck: 17,
  AliveResponse: 18
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AddEntity = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AddEntity}
 */
org.herbal3d.protocol.basil.server.AddEntity.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AddEntity=} obj
 * @returns {org.herbal3d.protocol.basil.server.AddEntity}
 */
org.herbal3d.protocol.basil.server.AddEntity.getRootAsAddEntity = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AddEntity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.AddEntity.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.AddEntity.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.assetInformation=} obj
 * @returns {org.herbal3d.protocol.basil.assetInformation}
 */
org.herbal3d.protocol.basil.server.AddEntity.prototype.assetInfo = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.assetInformation).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.aaBoundingBox=} obj
 * @returns {org.herbal3d.protocol.basil.aaBoundingBox}
 */
org.herbal3d.protocol.basil.server.AddEntity.prototype.aabb = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new org.herbal3d.protocol.basil.aaBoundingBox).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AddEntity.startAddEntity = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.AddEntity.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.AddEntity.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} assetInfoOffset
 */
org.herbal3d.protocol.basil.server.AddEntity.addAssetInfo = function(builder, assetInfoOffset) {
  builder.addFieldOffset(2, assetInfoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} aabbOffset
 */
org.herbal3d.protocol.basil.server.AddEntity.addAabb = function(builder, aabbOffset) {
  builder.addFieldStruct(3, aabbOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AddEntity.endAddEntity = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.RemoveEntity = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.RemoveEntity}
 */
org.herbal3d.protocol.basil.server.RemoveEntity.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.RemoveEntity=} obj
 * @returns {org.herbal3d.protocol.basil.server.RemoveEntity}
 */
org.herbal3d.protocol.basil.server.RemoveEntity.getRootAsRemoveEntity = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.RemoveEntity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.RemoveEntity.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.RemoveEntity.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.RemoveEntity.startRemoveEntity = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.RemoveEntity.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.RemoveEntity.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.RemoveEntity.endRemoveEntity = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AddInstance = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AddInstance}
 */
org.herbal3d.protocol.basil.server.AddInstance.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AddInstance=} obj
 * @returns {org.herbal3d.protocol.basil.server.AddInstance}
 */
org.herbal3d.protocol.basil.server.AddInstance.getRootAsAddInstance = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AddInstance).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.AddInstance.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AddInstance.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.coordPosition=} obj
 * @returns {org.herbal3d.protocol.basil.coordPosition}
 */
org.herbal3d.protocol.basil.server.AddInstance.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.coordPosition).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.AddInstance.prototype.propertiesToSet = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AddInstance.startAddInstance = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.AddInstance.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.AddInstance.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
org.herbal3d.protocol.basil.server.AddInstance.addPos = function(builder, posOffset) {
  builder.addFieldOffset(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertiesToSetOffset
 */
org.herbal3d.protocol.basil.server.AddInstance.addPropertiesToSet = function(builder, propertiesToSetOffset) {
  builder.addFieldOffset(3, propertiesToSetOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AddInstance.endAddInstance = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.RemoveInstance = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.RemoveInstance}
 */
org.herbal3d.protocol.basil.server.RemoveInstance.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.RemoveInstance=} obj
 * @returns {org.herbal3d.protocol.basil.server.RemoveInstance}
 */
org.herbal3d.protocol.basil.server.RemoveInstance.getRootAsRemoveInstance = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.RemoveInstance).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.RemoveInstance.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.RemoveInstance.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.RemoveInstance.startRemoveInstance = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.RemoveInstance.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.RemoveInstance.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.RemoveInstance.endRemoveInstance = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceId = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.GetUniqueInstanceId}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceId.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.GetUniqueInstanceId=} obj
 * @returns {org.herbal3d.protocol.basil.server.GetUniqueInstanceId}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceId.getRootAsGetUniqueInstanceId = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.GetUniqueInstanceId).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceId.startGetUniqueInstanceId = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceId.endGetUniqueInstanceId = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.getRootAsGetUniqueInstanceIdResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.startGetUniqueInstanceIdResponse = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(0, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.GetUniqueInstanceIdResponse.endGetUniqueInstanceIdResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateEntityProperty}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateEntityProperty=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateEntityProperty}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.getRootAsUpdateEntityProperty = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateEntityProperty).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.prototype.props = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.startUpdateEntityProperty = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(2, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateEntityProperty.endUpdateEntityProperty = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstanceProperty}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateInstanceProperty=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstanceProperty}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.getRootAsUpdateInstanceProperty = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateInstanceProperty).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.prototype.props = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.startUpdateInstanceProperty = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(2, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateInstanceProperty.endUpdateInstanceProperty = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstancePosition}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.UpdateInstancePosition=} obj
 * @returns {org.herbal3d.protocol.basil.server.UpdateInstancePosition}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.getRootAsUpdateInstancePosition = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.UpdateInstancePosition).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.instancePositionInfo=} obj
 * @returns {org.herbal3d.protocol.basil.instancePositionInfo}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.prototype.pos = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new org.herbal3d.protocol.basil.instancePositionInfo).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.startUpdateInstancePosition = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} posOffset
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.addPos = function(builder, posOffset) {
  builder.addFieldOffset(2, posOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.UpdateInstancePosition.endUpdateInstancePosition = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.EntityPropertyRequest}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.EntityPropertyRequest=} obj
 * @returns {org.herbal3d.protocol.basil.server.EntityPropertyRequest}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.getRootAsEntityPropertyRequest = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.EntityPropertyRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.prototype.propertyMatch = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.startEntityPropertyRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(1, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertyMatchOffset
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.addPropertyMatch = function(builder, propertyMatchOffset) {
  builder.addFieldOffset(2, propertyMatchOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.EntityPropertyRequest.endEntityPropertyRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.EntityPropertyResponse}
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.EntityPropertyResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.EntityPropertyResponse}
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.getRootAsEntityPropertyResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.EntityPropertyResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.prototype.objectId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.prototype.props = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.startEntityPropertyResponse = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} objectIdOffset
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.addObjectId = function(builder, objectIdOffset) {
  builder.addFieldOffset(0, objectIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(1, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.EntityPropertyResponse.endEntityPropertyResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertyRequest}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.InstancePropertyRequest=} obj
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertyRequest}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.getRootAsInstancePropertyRequest = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.InstancePropertyRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.prototype.propertyMatch = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.startInstancePropertyRequest = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(1, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propertyMatchOffset
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.addPropertyMatch = function(builder, propertyMatchOffset) {
  builder.addFieldOffset(2, propertyMatchOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.InstancePropertyRequest.endInstancePropertyRequest = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertyResponse}
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.InstancePropertyResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.InstancePropertyResponse}
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.getRootAsInstancePropertyResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.InstancePropertyResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.prototype.instanceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.prototype.props = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.startInstancePropertyResponse = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} instanceId
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.addInstanceId = function(builder, instanceId) {
  builder.addFieldInt32(0, instanceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} propsOffset
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.addProps = function(builder, propsOffset) {
  builder.addFieldOffset(1, propsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.InstancePropertyResponse.endInstancePropertyResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.OpenSession = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.OpenSession}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.OpenSession=} obj
 * @returns {org.herbal3d.protocol.basil.server.OpenSession}
 */
org.herbal3d.protocol.basil.server.OpenSession.getRootAsOpenSession = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.OpenSession).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.accessAuthorization=} obj
 * @returns {org.herbal3d.protocol.basil.accessAuthorization}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.auth = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.accessAuthorization).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.OpenSession.prototype.params = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.OpenSession.startOpenSession = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} authOffset
 */
org.herbal3d.protocol.basil.server.OpenSession.addAuth = function(builder, authOffset) {
  builder.addFieldOffset(0, authOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} paramsOffset
 */
org.herbal3d.protocol.basil.server.OpenSession.addParams = function(builder, paramsOffset) {
  builder.addFieldOffset(1, paramsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.OpenSession.endOpenSession = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.OpenSessionResponse}
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.OpenSessionResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.OpenSessionResponse}
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.getRootAsOpenSessionResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.OpenSessionResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.propertyList=} obj
 * @returns {org.herbal3d.protocol.basil.propertyList}
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.prototype.features = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.propertyList).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.startOpenSessionResponse = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} featuresOffset
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.addFeatures = function(builder, featuresOffset) {
  builder.addFieldOffset(0, featuresOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.OpenSessionResponse.endOpenSessionResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.CloseSession = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.CloseSession}
 */
org.herbal3d.protocol.basil.server.CloseSession.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.CloseSession=} obj
 * @returns {org.herbal3d.protocol.basil.server.CloseSession}
 */
org.herbal3d.protocol.basil.server.CloseSession.getRootAsCloseSession = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.CloseSession).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
org.herbal3d.protocol.basil.server.CloseSession.prototype.reason = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.CloseSession.startCloseSession = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reasonOffset
 */
org.herbal3d.protocol.basil.server.CloseSession.addReason = function(builder, reasonOffset) {
  builder.addFieldOffset(0, reasonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.CloseSession.endCloseSession = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AliveCheck = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AliveCheck}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AliveCheck=} obj
 * @returns {org.herbal3d.protocol.basil.server.AliveCheck}
 */
org.herbal3d.protocol.basil.server.AliveCheck.getRootAsAliveCheck = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AliveCheck).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveCheck.prototype.sequenceNumber = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AliveCheck.startAliveCheck = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} time
 */
org.herbal3d.protocol.basil.server.AliveCheck.addTime = function(builder, time) {
  builder.addFieldInt64(0, time, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumber
 */
org.herbal3d.protocol.basil.server.AliveCheck.addSequenceNumber = function(builder, sequenceNumber) {
  builder.addFieldInt32(1, sequenceNumber, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AliveCheck.endAliveCheck = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.AliveResponse = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.AliveResponse}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.AliveResponse=} obj
 * @returns {org.herbal3d.protocol.basil.server.AliveResponse}
 */
org.herbal3d.protocol.basil.server.AliveResponse.getRootAsAliveResponse = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.AliveResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.sequenceNumber = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {flatbuffers.Long}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.timeReceived = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {number}
 */
org.herbal3d.protocol.basil.server.AliveResponse.prototype.sequenceNumberReceived = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.AliveResponse.startAliveResponse = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} time
 */
org.herbal3d.protocol.basil.server.AliveResponse.addTime = function(builder, time) {
  builder.addFieldInt64(0, time, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumber
 */
org.herbal3d.protocol.basil.server.AliveResponse.addSequenceNumber = function(builder, sequenceNumber) {
  builder.addFieldInt32(1, sequenceNumber, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timeReceived
 */
org.herbal3d.protocol.basil.server.AliveResponse.addTimeReceived = function(builder, timeReceived) {
  builder.addFieldInt64(2, timeReceived, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} sequenceNumberReceived
 */
org.herbal3d.protocol.basil.server.AliveResponse.addSequenceNumberReceived = function(builder, sequenceNumberReceived) {
  builder.addFieldInt32(3, sequenceNumberReceived, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.AliveResponse.endAliveResponse = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
org.herbal3d.protocol.basil.server.BasilServerMsg = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {org.herbal3d.protocol.basil.server.BasilServerMsg=} obj
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.getRootAsBasilServerMsg = function(bb, obj) {
  return (obj || new org.herbal3d.protocol.basil.server.BasilServerMsg).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {org.herbal3d.protocol.basil.BTransportHdrStruct=} obj
 * @returns {org.herbal3d.protocol.basil.BTransportHdrStruct}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.BTransportHdr = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new org.herbal3d.protocol.basil.BTransportHdrStruct).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @returns {org.herbal3d.protocol.basil.server.BasilServerMsgMsg}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.MsgType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {org.herbal3d.protocol.basil.server.BasilServerMsgMsg} */ (this.bb.readUint8(this.bb_pos + offset)) : org.herbal3d.protocol.basil.server.BasilServerMsgMsg.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.prototype.Msg = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.startBasilServerMsg = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} BTransportHdrOffset
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addBTransportHdr = function(builder, BTransportHdrOffset) {
  builder.addFieldOffset(0, BTransportHdrOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {org.herbal3d.protocol.basil.server.BasilServerMsgMsg} MsgType
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addMsgType = function(builder, MsgType) {
  builder.addFieldInt8(1, MsgType, org.herbal3d.protocol.basil.server.BasilServerMsgMsg.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} MsgOffset
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.addMsg = function(builder, MsgOffset) {
  builder.addFieldOffset(2, MsgOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
org.herbal3d.protocol.basil.server.BasilServerMsg.endBasilServerMsg = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.org = org;
